version: '3.7'

services:
  xlate:
    build: .
    image: xlate
    environment:
      - BLUEMIX_API_KEY=${BLUEMIX_API_KEY}
      - BLUEMIX_API_URL=${BLUEMIX_API_URL}
    ports:
      - "9090:9090"
    restart: unless-stopped
